package main

import (
	"log"
	"os"

	"warehouse-inventory-server/config"
	"warehouse-inventory-server/handlers"
	"warehouse-inventory-server/middleware"
	"warehouse-inventory-server/repositories"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/joho/godotenv"

	_ "warehouse-inventory-server/docs" // docs is generated by Swag CLI, you have to import it.

	fiberSwagger "github.com/swaggo/fiber-swagger"
)

// @title Warehouse Inventory API
// @version 1.0
// @description This is a backend service for a Warehouse Inventory System.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.email support@warehouse.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	// Load .env file
	_ = godotenv.Load()

	// Initialize Database
	db, err := config.InitDB()
	if err != nil {
		log.Fatalf("failed to connect database: %v", err)
	}
	log.Println("database connected")

	// Initialize Fiber app with Custom Error Handler
	app := fiber.New(fiber.Config{
		ErrorHandler: middleware.ErrorHandler,
	})

	// CORS Middleware for handling cross-origin requests (necessary for frontend-backend communication)
	app.Use(cors.New())

	// Rate Limiter Middleware
	app.Use(middleware.RateLimiter())

	// Swagger Route
	app.Get("/swagger/*", fiberSwagger.WrapHandler)

	// Health check endpoint
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.Status(fiber.StatusOK).JSON(fiber.Map{
			"status":  "healthy",
			"message": "Warehouse Inventory Server is running",
		})
	})

	// Auth routes
	userRepo := repositories.NewUserRepository(db)
	userHandler := handlers.NewUserHandler(userRepo)

	authRoute := app.Group("/api/auth")
	userHandler.RegisterRoute(authRoute)

	// Barang routes
	barangRepo := repositories.NewBarangRepository(db)
	barangHandler := handlers.NewBarangHandler(barangRepo)

	barangRoute := app.Group("/api/barang", middleware.Authentication())
	barangHandler.RegisterRoute(barangRoute)

	// Stock routes
	stokRepo := repositories.NewStokRepository(db)
	stokHandler := handlers.NewStokHandler(stokRepo)

	stokRoute := app.Group("/api/stok", middleware.Authentication())
	stokHandler.RegisterStockRoute(stokRoute)

	historyRoute := app.Group("/api/history-stok", middleware.Authentication())
	stokHandler.RegisterHistoryRoute(historyRoute)

	// Pembelian routes
	pembelianRepo := repositories.NewPembelianRepository(db)
	pembelianHandler := handlers.NewPembelianHandler(pembelianRepo, stokRepo)

	pembelianRoute := app.Group("/api/pembelian", middleware.Authentication())
	pembelianHandler.RegisterRoute(pembelianRoute)

	// Penjualan routes
	penjualanRepo := repositories.NewPenjualanRepository(db)
	penjualanHandler := handlers.NewPenjualanHandler(penjualanRepo, stokRepo)

	penjualanRoute := app.Group("/api/penjualan", middleware.Authentication())
	penjualanHandler.RegisterRoute(penjualanRoute)

	port := os.Getenv("PORT")

	if err := app.Listen(":" + port); err != nil {
		log.Fatalf("server failed: %v", err)
	}
}
